# Generated by Django 3.2.5 on 2021-08-04 20:30

from django.db import migrations, models
import django.db.models.deletion
import restql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[restql.models.validate_dummy])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[restql.models.validate_dummy])),
            ],
        ),
        migrations.CreateModel(
            name='IngredientMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restql.ingredient')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_mixes', to='restql.product')),
            ],
            options={
                'unique_together': {('ingredient', 'product')},
            },
        ),
    ]
