# Generated by Django 3.2.5 on 2021-08-05 13:14

from django.db import migrations, models
import restql.models


class Migration(migrations.Migration):

    dependencies = [
        ('restql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientmix',
            name='name',
            field=models.CharField(default=2, max_length=100, validators=[restql.models.validate_dummy]),
            preserve_default=False,
        ),
    ]
