# Generated by Django 3.2.5 on 2021-08-05 13:20

from django.db import migrations, models
import restql.models


class Migration(migrations.Migration):

    dependencies = [
        ('restql', '0002_ingredientmix_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientmix',
            name='name',
            field=models.CharField(default='', max_length=100, validators=[restql.models.validate_dummy]),
        ),
    ]
